### ISSUE TITLE
Unhandled Exception With Shard Disconnect After "Fix"

### ISSUE THREAD

**Issue by ZandercraftGames** [TheSharks/WildBeast#395] opened 2018-11-24 14:55 UTC
**Describe the bug**
The bot will crash because of an unhandled exception. Even after the fix that Dougley made.

**To Reproduce**
1. Run The Bot in Docker
2. Wait anywhere from 3 mins - 3 days
3. Bot will crash

**Expected behavior**
Bot should continue running and not crash even if a shard disconnects. It should reconnect.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Docker Version: 18.03.0-ce, build 0520e24302
 - Wildbeast Version: Up to date.

**Error**
WARN: Discord connection broke, shard disconnected
ERROR: [object Object],0
FATAL: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Client.emit (events.js:171:17)
    at Client.emit (/opt/wildbeast/index.js:29:25)
    at Shard.emit (/opt/wildbeast/node_modules/eris/lib/gateway/Shard.js:1888:26)
    at WebSocketClient.ws.onerror [as internalOnError] (/opt/wildbeast/node_modules/eris/lib/gateway/Shard.js:1612:18)
    at process.nextTick (/opt/wildbeast/node_modules/uws/uws.js:80:19)
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by ZandercraftGames** [comment] 2018-11-24 14:56
Dougley? Is this what you meant by restart?

**Comment by Dougley** [comment] 2018-11-24 15:04
This is the **second** time you opened an issue for the same problem, and the **third** time you mentioned it here.   
I already explained this is extremely unpredictable behaviour and that *your process* should just restart, we can't continue like normal after fatal errors.
# Please do not open any more issues about this problem

**Comment by Dougley** [comment] 2018-11-27 12:31
Update on this, managed to reproduce this in dev by physically disconnecting my machine from the internet, turns out this is related to us not properly handling WS errors inside runtime (N.js events doesn't consider our onAny listener an error listener), will investigate further and update this.

**Comment by Dougley** [comment] 2018-11-27 12:52
Fixed as of https://github.com/TheSharks/WildBeast/commit/ef3d096fceb69f309377b0441f5894b699a5d3fc, sorry about that.

**Closed by Dougley** 2018-11-27 12:52 UTC
Labels: bug, duplicate

**Comment by ZandercraftGames** [comment] 2018-11-27 13:08
Thank you @Dougley and I'm sorry for the misunderstanding.
